name = "alphabook-frontend-proxy"
main = "src/index.ts"
compatibility_date = "2026-04-07"
workers_dev = true

routes = [
  { pattern = "alpha-book.org/*", zone_name = "alpha-book.org" },
  { pattern = "www.alpha-book.org/*", zone_name = "alpha-book.org" },
]

[vars]
FRONTEND_ORIGIN = "http://origin.alpha-book.org"
