export const HARD_LIMITS = {
  MAX_TURNS: 40,
  MAX_RUNTIME_TASKS_PER_RUN: 16,
  MAX_WORKSPACE_BYTES: 50 * 1024 * 1024,
  MAX_RUNTIME_IDLE_MINUTES: 15,
  MAX_RUN_WALL_CLOCK_SECONDS: 1800,
  MAX_TOOL_TIMEOUT_SECONDS: 120,
  MAX_RUNTIME_TOOL_TIMEOUT_SECONDS: 1500,
} as const;
